### ISSUE TITLE
`/help` command

### ISSUE THREAD

**Issue by Aomitsu** [raidprotect/raidprotect#119]
RaidProtect have actually 4 simple commands. (`?help`, `?stats`, `?link`, `?about`) It may be interesting to re implement them in a different way :
+ `/about` can replace `?link`, `?about` and `?help` : Users no longer need a /help command, since slash commands are documented. This command could be used to redirect users to the documentation, or to the server support.
~~+ `/stats` can be re implemented as it is~~ ( _Useless, and complex to implement_ )

**Comment by baptiste0928** [comment]
Good idea to name the command `/about`, it will avoid conflicts with other bots since most of them use `/help`.

I don't really think a `/stats` command would be useful for end users, and it will become complex to implement with clustering.

**Comment by Aomitsu** [comment]
Yeah, `?stats` command is useless, it was just to respect the commands of the original bot.
And, because this command is really simple, I think it's a good thing for me, to discover integrations.

So, I can do it, if you agree.

**Comment by baptiste0928** [comment]
You can go ahead, I assigned you

**Comment by Aomitsu** [comment]
### I need your opinion.
I was inspired by the old command `?about` command for the layout, and currently the text.
Because every strings can be changed in locale files, it's actually not important.

The purpose of the command being to inform, but also indirectly to make a kind of publicity of the bot, I propose to send it in the channel directly, and so that the message is not seen only by the person who made the command.
However, it doesn't seem to be the bot idea to send the messages directly in the channel. But this case is special because it allows to spread the bot.

Then, the layout I copied from the old bot looks like this, for me there is nothing to change but if you have ideas, suggest!
![image](https://user-images.githubusercontent.com/52425530/181218190-e4a1c620-7310-4bba-af9c-47cd67d5d7c8.png)
