### ISSUE TITLE
Translate command descriptions

### ISSUE THREAD

**Issue by baptiste0928** [raidprotect/raidprotect#125]
We should provide translations for command and command options descriptions. After a survey in our Discord server, we decided to keep command and command options names in English.

`twilight_interactions` [supports localization](https://docs.rs/twilight-interactions/latest/twilight_interactions/command/index.html#localization), but need a function for each key. We can create a simple `macro_rules!` to generate the functions:

```rs
desc_translation!(help_description);

// Expands to:
fn help_description() -> impl IntoIterator<Item = (ToString, ToString)> {
    [
        ("fr", Lang::Fr.help_description()),
        ("en-US", Lang::En.help_description()),
    ]
}
```

**Comment by Aomitsu** [comment]
Can I do it? uwu

**Comment by Aomitsu** [comment]
It's not fully released by discord on clients
( but we can have a build override to add the feature temporarily, so I can do it )

**Comment by baptiste0928** [comment]
It's still in beta, here is an override to enable the feature: [Command localization override](https://discord.com/__development/link?s=VQw65opXPNOuzDRAa9ID91y7BV0U0ATg%2FmZfrhCBCqc%3D.eyJ0YXJnZXRCdWlsZE92ZXJyaWRlIjp7ImRpc2NvcmRfd2ViIjp7InR5cGUiOiJicmFuY2giLCJpZCI6ImZlYXR1cmUvd2ViLXNsYXNoLWNvbW1hbmQtbG9jYWxpemF0aW9uIn19LCJyZWxlYXNlQ2hhbm5lbCI6bnVsbCwidmFsaWRGb3JVc2VySWRzIjpbXSwiYWxsb3dMb2dnZWRPdXQiOmZhbHNlLCJleHBpcmVzQXQiOiJXZWQsIDEwIEF1ZyAyMDIyIDE3OjE4OjQ1IEdNVCJ9). We can still implement it to be ready when it becomes available.
