### ISSUE TITLE
Translate the bot according to the user language

### ISSUE THREAD

**Issue by baptiste0928** [raidprotect/raidprotect#65]
RaidProtect uses [`rosetta`](https://github.com/baptiste0928/rosetta) to handle translation files. Actually, usage of French is hard-coded. The bot should change the display language depending on the user settings.

- For interactions, use the user `locale` field that Discord sends.
- For other messages, like logs or pm sent to guild members, the locale should be stored in the database along with the guild configuration. The `guild_locale` field [is not reliable](https://github.com/discord/discord-api-docs/discussions/4332).

**Comment by Aomitsu** [comment]
self assigning
